PART 1

In [2]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

input_layer_neurons = X.shape[1]
hidden_layer_neurons = 2
output_neurons = 1

np.random.seed(42)
hidden_weights = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
hidden_bias = np.random.uniform(size=(1, hidden_layer_neurons))
output_weights = np.random.uniform(size=(hidden_layer_neurons, output_neurons))
output_bias = np.random.uniform(size=(1, output_neurons))

learning_rate = 0.1
epochs = 10000

for _ in range(epochs):
    hidden_layer_activation = np.dot(X, hidden_weights) + hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output, output_weights) + output_bias
    predicted_output = sigmoid(output_layer_activation)

    error = y - predicted_output

    d_predicted_output = error * sigmoid_derivative(predicted_output)
    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    output_weights += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
    output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
    hidden_weights += X.T.dot(d_hidden_layer) * learning_rate
    hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

print("weights of hidden layers:\n", hidden_weights)
print("biases of hidden layers:\n", hidden_bias)
print("weights of hidden layers:\n", output_weights)
print("biases:\n", output_bias)
print("output:\n", predicted_output)


weights of hidden layers:
 [[3.79198478 5.81661184]
 [3.80004873 5.8545897 ]]
biases of hidden layers:
 [[-5.82020057 -2.46277158]]
weights of hidden layers:
 [[-8.32186051]
 [ 7.66063503]]
biases:
 [[-3.45550373]]
output:
 [[0.05322146]
 [0.95171535]
 [0.95160449]
 [0.05175396]]


PART 2

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

model = Sequential()
model.add(Dense(2, input_dim=2, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['binary_accuracy'])

model.fit(X, y, epochs=10000, verbose=0)

loss, accuracy = model.evaluate(X, y)
print("accuracy : ", accuracy)

predictions = model.predict(X)
print("predictions : \n", predictions)


1/1 [==============================] - 0s 229ms/step - loss: 0.0021 - binary_accuracy: 1.0000
accuracy :  1.0
1/1 [==============================] - 0s 87ms/step
predictions : 
 [[0.04583393]
 [0.95738906]
 [0.9502024 ]
 [0.04369954]]
